"""
Django settings for sniffer project.

Generated by 'django-admin startproject' using Django 1.10.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
from __future__ import absolute_import, unicode_literals
import os
from celery import Celery


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'sniffer.settings')

app = Celery('sniffer')
app.conf.broker_url = 'redis://10.37.253.38:6379/0'
app.conf.result_backend = 'redis://10.37.253.38:6379/0'
app.conf.broker_transport_options = {'visibility_timeout': 3600}
app.config_from_object('django.conf:settings', namespace='CELERY')
app.autodiscover_tasks()


@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
